{% set version = "4.8.0" %}

package:
  name: json-e
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/json-e/json-e-{{ version }}.tar.gz
    sha256: 91a50ba4e1a9e6d40c36c0601d68acda9ae44ca2817525e09938b2c82ce23572
  - folder: src
    url: https://github.com/json-e/json-e/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 4901da0b55d51c638f24f95a1733e7ecb3cb4a3ac40ac7ccb50477bfeb7766f0

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8

test:
  source_files:
    - src/py/test
    - src/specification.yml
  requires:
    - coverage
    - freezegun
    - hypothesis
    - pep8
    - pip
    - pytest
    - python-dateutil
    - pyyaml
  imports:
    - jsone
  commands:
    - pip check
    - cd src/py/test
    - coverage run --source=jsone --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=96

about:
  home: https://json-e.js.org
  license: MPL-2.0
  license_family: MOZILLA
  license_file: src/LICENSE
  summary: A data-structure parameterization system written for embedding context in JSON objects
  dev_url: https://github.com/json-e/json-e
  description: >
    The central idea is to treat a data structure as a "template" and transform it, using another data structure as context, to produce an output data structure.

    There are countless libraries to do this with strings, such as mustache. What makes JSON-e unique is that it operates on data structures, not on their textual representation. This allows input to be written in a number of formats (JSON, YAML, etc.) or even generated dynamically. It also means that the output cannot be
    "invalid", even when including large chunks of contextual data.

    JSON-e is also designed to be safe for use on untrusted data. It never uses eval or any other function that might result in arbitrary code execution. It also disallows unbounded iteration, so any JSON-e rendering operation will finish in finite time.

extra:
  recipe-maintainers:
    - bollwyvl
