{% set version = "4.5.2" %}

package:
  name: json-e
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/json-e/json-e-{{ version }}.tar.gz
    sha256: 0d1203645a5753dec2da1ceab279f82169023948eff858b87968117e8a592e10
  - folder: src
    url: https://github.com/json-e/json-e/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 4ddffa2a62b486834f6aa83e49508d6ec8ee34ed27020b5d9a8a3d8a54d94bb8

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - src/py/test
    - src/specification.yml
  requires:
    - freezegun
    - hypothesis
    - nose
    - pyyaml
    - python-dateutil
    - pep8
    - pip
  imports:
    - jsone
  commands:
    - python -m pip check
    - cd src/py/test && nosetests

about:
  home: https://json-e.js.org
  license: MPL-2.0
  license_family: MOZILLA
  license_file: src/LICENSE
  summary: A data-structure parameterization system written for embedding context in JSON objects
  dev_url: https://github.com/json-e/json-e
  description: >
    The central idea is to treat a data structure as a "template" and transform it, using another data structure as context, to produce an output data structure.

    There are countless libraries to do this with strings, such as mustache. What makes JSON-e unique is that it operates on data structures, not on their textual representation. This allows input to be written in a number of formats (JSON, YAML, etc.) or even generated dynamically. It also means that the output cannot be
    "invalid", even when including large chunks of contextual data.

    JSON-e is also designed to be safe for use on untrusted data. It never uses eval or any other function that might result in arbitrary code execution. It also disallows unbounded iteration, so any JSON-e rendering operation will finish in finite time.

extra:
  recipe-maintainers:
    - bollwyvl
