travis:
  secure:
    BINSTAR_TOKEN: EGaJ3ECAdKS9jznCOOkHzkuaXstJpcu7Joq5y0j3Z2aw5q8oToF2wbM3HWdg1PZFe84UnpRiqpL2nwHND2BCgoU8JVi1SF5uXEPqSJAtTGvXnklXMiJVTqJmcajrsPUDqRMkjtQk4BjOgdTm1U3HZJZH+l/3PoR97jSHOjn0A8jRQORuyBen32iCJWs7yd+J75iBIshGlJzBsbKRzGP9J9fBRMnpc5pnzqarYNcKedYRQUwc6t8QhLBItXBUAZLXX/n24H6Albube0zW2f13+OqmAuKZVNehhNjC1JfXjNP1TJ7MApGOj47afBMd+k31elITzKjgRTwYsMuQBY+QC0dyhqzLLmw7UV4SvbBGnr/qCYFIjczwIrKqAbwCDL2ykd/ZuL9nqDnPYVy4zw8rK0MXnuL7xxYwY+zMAunKXp/FiwtHG87KS9rlpyRg18He+RdYwABt3JGixLYaV59KxNhO4BY/jSG2li4cez8SHsRfy2x66tiZC2zP1ZgqjBgXUaZyHW111QwhTpSbzberHb+PZvwJZwPbSF6vqtxu37fp3fRrVBB2+hxbFGJ3pcwy+G7lAxmpbjiB18RsjYlsYkZXdbnr5YCG+AMFWFING98vHSZ1/F0RyLiPFBdLgLrfENHWRsDlHjsmWC/llIPkxSFLnVP3U548b+oI4oNr3U4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
